name: Windows (Direct3D12)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Compile & Build EXE
      run: |
        cd paint
        ..\base\make --compile
        cd build
        msbuild ArmorPaint.sln /p:Configuration=Release /p:Platform=x64

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ArmorPaint-Windows-Executable
        path: |
          paint/build/x64/Release/ArmorPaint.exe
          paint/data/
